#!/usr/bin/env bash
#
# Copyright (C) 2023 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# shellcheck disable=SC1090,SC1091

set -Ee

# [
trap 'rm -f $OUT_DIR/config.sh' ERR

GET_OFFICIAL_STATUS()
{
    local USES_UNICA_CERT=false

    if [ -f "$SRC_DIR/security/unica_platform.pk8" ]; then
        openssl ec -pubout -in "$SRC_DIR/security/unica_platform.pk8" -out "$OUT_DIR/unica_platform.pub" &> /dev/null \
            || touch "$OUT_DIR/unica_platform.pub"
        if cmp -s "$SRC_DIR/security/unica_platform.pub" "$OUT_DIR/unica_platform.pub"; then
            USES_UNICA_CERT=true
        fi
        rm -f "$OUT_DIR/unica_platform.pub"
    fi

    echo "$USES_UNICA_CERT"
}

GEN_CONFIG_FILE()
{
    if [ -f "$OUT_DIR/config.sh" ]; then
        echo "config.sh already exists. Regenerating..."
        rm -f "$OUT_DIR/config.sh"
    fi

    {
        echo "# Automatically generated by unica/scripts/internal/gen_config_file.sh"
        echo "ROM_IS_OFFICIAL=\"$(GET_OFFICIAL_STATUS)\""
        echo "ROM_VERSION=\"${ROM_VERSION:?}\""
        echo "ROM_CODENAME=\"${ROM_CODENAME:?}\""
        echo "ROM_BUILD_TIMESTAMP=\"$(date '+%s')\""
        echo "SOURCE_CODENAME=\"${SOURCE_CODENAME:?}\""
        echo "SOURCE_FIRMWARE=\"${SOURCE_FIRMWARE:?}\""
        echo "SOURCE_PRODUCT_FIRST_API_LEVEL=\"${SOURCE_PRODUCT_FIRST_API_LEVEL:?}\""
        if [ -n "${SOURCE_EXTRA_FIRMWARES[*]:-}" ]; then
           echo "SOURCE_EXTRA_FIRMWARES=\"$(IFS=:; printf '%s' "${SOURCE_EXTRA_FIRMWARES[*]}")\""
        fi
        echo "SOURCE_PRODUCT_CODE=\"${SOURCE_PRODUCT_CODE:?}\""
        echo "SOURCE_SSRM_CONFIG_NAME=\"${SOURCE_SSRM_CONFIG_NAME:?}\""
        echo "SOURCE_IS_ESIM_SUPPORTED=\"${SOURCE_IS_ESIM_SUPPORTED:?}\""
        echo "SOURCE_DVFS_CONFIG_NAME=\"${SOURCE_DVFS_CONFIG_NAME:?}\""
        echo "SOURCE_MDNIE_SUPPORTED_MODES=\"${SOURCE_MDNIE_SUPPORTED_MODES:?}\""
        echo "SOURCE_HFR_SUPPORTED_REFRESH_RATE=\"${SOURCE_HFR_SUPPORTED_REFRESH_RATE:?}\""
        echo "SOURCE_HFR_DEFAULT_REFRESH_RATE=\"${SOURCE_HFR_DEFAULT_REFRESH_RATE:?}\""
        echo "SOURCE_MDNIE_SUPPORTED_MODES=\"${SOURCE_MDNIE_SUPPORTED_MODES:?}\""
        echo "SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION=\"${SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION:?}\""
        echo "SOURCE_MULTI_MIC_MANAGER_VERSION=\"${SOURCE_MULTI_MIC_MANAGER_VERSION:?}\""
        echo "SOURCE_HFR_MODE=\"${SOURCE_HFR_MODE:?}\""
        echo "SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=\"${SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER:?}\""
        echo "TARGET_NAME=\"${TARGET_NAME:?}\""
        echo "TARGET_CODENAME=\"${TARGET_CODENAME:?}\""
        echo "TARGET_OS_FILE_SYSTEM=\"${TARGET_OS_FILE_SYSTEM:=erofs}\""
        echo "SOURCE_HAS_SYSTEM_EXT=\"${SOURCE_HAS_SYSTEM_EXT:?}\""
        echo "TARGET_HAS_SYSTEM_EXT=\"${TARGET_HAS_SYSTEM_EXT:?}\""
        echo "SOURCE_HAS_PRODUCT=\"${SOURCE_HAS_PRODUCT:?}\""
        echo "TARGET_HAS_PRODUCT=\"${TARGET_HAS_PRODUCT:?}\""
        echo "TARGET_SINGLE_SYSTEM_IMAGE=\"${TARGET_SINGLE_SYSTEM_IMAGE:?}\""
        echo "TARGET_VENDOR_API_LEVEL=\"${TARGET_VENDOR_API_LEVEL:?}\""
        echo "TARGET_SSRM_CONFIG_NAME=\"${TARGET_SSRM_CONFIG_NAME:?}\""
        echo "TARGET_IS_ESIM_SUPPORTED=\"${TARGET_IS_ESIM_SUPPORTED:?}\""
        echo "TARGET_DVFS_CONFIG_NAME=\"${TARGET_DVFS_CONFIG_NAME:?}\""
        echo "TARGET_MDNIE_SUPPORTED_MODES=\"${TARGET_MDNIE_SUPPORTED_MODES:?}\""
        if [ -n "${TARGET_HFR_SUPPORTED_REFRESH_RATE[*]:-}" ]; then
           echo "TARGET_HFR_SUPPORTED_REFRESH_RATE=\"$(IFS=:; printf '%s' "${TARGET_HFR_SUPPORTED_REFRESH_RATE[*]}")\""
        fi
        echo "TARGET_HFR_DEFAULT_REFRESH_RATE=\"${TARGET_HFR_DEFAULT_REFRESH_RATE:?}\""
        echo "TARGET_HFR_MODE=\"${TARGET_HFR_MODE:?}\""
        echo "TARGET_MDNIE_WEAKNESS_SOLUTION_FUNCTION=\"${TARGET_MDNIE_WEAKNESS_SOLUTION_FUNCTION:?}\""
        echo "TARGET_AUDIO_SUPPORT_DUAL_SPEAKER=\"${TARGET_AUDIO_SUPPORT_DUAL_SPEAKER:?}\""
    } > "$OUT_DIR/config.sh"
}

source "$SRC_DIR/target/$1/config.sh"
source "$SRC_DIR/unica/configs/version.sh"

if [ ! -f "$SRC_DIR/unica/configs/$TARGET_SINGLE_SYSTEM_IMAGE.sh" ]; then
    echo "\"$TARGET_SINGLE_SYSTEM_IMAGE\" is not a valid system image"
    exit 1
else
    source "$SRC_DIR/unica/configs/$TARGET_SINGLE_SYSTEM_IMAGE.sh"
fi
# ]

GEN_CONFIG_FILE
[ -f "$OUT_DIR/config.sh" ] || exit 1

exit 0